config/routes.rb
Rails.application.routes.draw do
  resource :example, constraints: -> { Rails.env.development? }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'streams#index'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  
  delete 'logout', to: 'sessions#destroy'

  get 'maps', to: 'maps#show'

  get 'streams', to: 'streams#index'
end


# https://guides.rubyonrails.org/v6.1/getting_started.html#creating-a-new-article
# authentication UserModel
# how to get live flows from website... scraping and getting once per day
## allow users to save favorites
## allow users to search by location
## currently at updating an article

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['public', 'private', 'archived']

    included do
        validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do
        def public_count
            where(status: 'public').count
        end
    end

    def archived?
        status == 'archived'
    end
end

app/models/favorite_stream.rb
class FavoriteStream < ApplicationRecord
  belongs_to :user
  belongs_to :stream
end

app/models/report.rb
class Report < ApplicationRecord
  include Visible
  belongs_to :flow
end

app/models/stream.rb
class Stream < ApplicationRecord
  has_many :favorite_streams
  has_many :favorited_by, through: :favorite_streams, source: :user
  has_many :stream_flows
end

app/models/stream_flow.rb
class StreamFlow < ApplicationRecord
    belongs_to :stream
    
    validates :flow_rate, presence: true
    validates :measured_at, presence: true
end

app/models/user.rb
# password: string virtual
# password_confirmation: string virtual

class User < ApplicationRecord
    has_secure_password

    # has_many :favorites
    # has_many :favorite_flows, through: :favorites, source: :flow

    has_many :favorite_streams, dependent: :destroy
    has_many :favorited_streams, through: :favorite_streams, source: :stream

    validates :email,   presence: true,
                        uniqueness: true,
                        format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'must be a valid email address' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end
end

app/controllers/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  layout false

  def show
    respond_to do |format|
      format.html
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def show
    @streams = nil
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully created account!"
        else
            render :new
        end
        # render plain: params[:user]
        # params.require(:user).permit(:email, :password, :password_confirmation)
        # @user = User.create(params.require(:user).permit(:email, :password, :password_confirmation))
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

    http_basic_authenticate_with name: 'gjf', password: 'secret', only: :destroy
    
  def create
    @flow = Flow.find(params[:flow_id])
    @report = @flow.reports.create(report_params)
    
    redirect_to flow_path(@flow)
  end

  def destroy
    @flow = Flow.find(params[:flow_id])
    @report = @flow.reports.find(params[:id])
    @report.destroy

    redirect_to flow_path(@flow)
  end

  private
    def report_params
      params.require(:report).permit(:author, :body, :rating, :status)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :index
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Log in successful!"
        else
            flash[:alert] = "Invalid email or password";
            render :index
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out!"
    end
end

app/controllers/streams_controller.rb
# Streams Controller

class StreamsController < ApplicationController

  def index
    @view_type = "all"
    @streams = StreamsService.new.call
    @current_user = Current.user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/examples/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>StimulusReflex Demo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% unless Rails.root.join("config/importmap.rb").exist? %>
    <script type="importmap">
      {
        "imports": {
          "fireworks-js": "https://ga.jspm.io/npm:fireworks-js@2.10.0/dist/index.es.js"
        }
      }
    </script>
    <% end %>

    <% if respond_to?(:vite_javascript_tag) %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag "application", defer: true %>
    <% elsif respond_to?(:javascript_pack_tag) %>
    <%= javascript_pack_tag "application", defer: true %>
    <% elsif respond_to?(:javascript_importmap_tags) %>
    <%= javascript_importmap_tags %>
    <% elsif respond_to?(:javascript_include_tag) %>
    <%= javascript_include_tag "application", defer: true %>
    <% end %>

    <script async src="https://ga.jspm.io/npm:es-module-shims@1.5.1/dist/es-module-shims.js" crossorigin="anonymous"></script>
    <script type="module">
      import { Fireworks } from 'fireworks-js'

      const fireworks = new Fireworks(document.querySelector('.fireworks'))
      document.addEventListener('fireworks', () => fireworks.launch(12))
    </script>

    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
  </head>

  <body style="cursor: auto;">
    <main class="container">
      <h1>StimulusReflex</h1>

      <p>Actual demonstrations will show up in this space, soon. In the meantime, verify that your installation was successful:</p>

      <button data-reflex="click->Example#increment">Increment</button>
      <button data-reflex="click->Example#reset">Reset</button>

      <br />

      <div>
        Last Refresh:
        <b><mark id="time"><%= Time.now %></mark></b>
      </div>

      <div>
        Clicked
        <b><mark id="count"><%= session[:count] || 0 %></mark></b>
        times
      </div>

      <br/>

      <progress value="<%= session[:count] %>" max="10"></progress>

      <div id="reload"></div>

      <h1>CableReady</h1>

      <p>CableReady lets you control one or many clients from the server in real-time.</p>

      <p>Everything in CableReady revolves around its <a href="https://cableready.stimulusreflex.com/reference/operations" target="_blank">38+</a> <b>operations</b>, which are commands that can update content, raise events, write cookies and even play audio. A group of one or more operations is called a <b>broadcast</b>. Broadcasts follow a <a href="https://dev.to/leastbad/the-cableready-language-implementation-project-4hjd">simple JSON format</a>.</p>

      <p>We're going to go through the main ways developers use CableReady with some live demonstrations and code samples. We recommend that you open the controller class and ERB template for this page to follow along.</p>

      <article>
        <h3>Subscribe to a channel to receive broadcasts</h3>

        WebSockets is the primary way most Rails developers use CableReady, via the <ins>cable_ready</ins> method.

        <p>Use the <ins>cable_ready_stream_from</ins> helper to create a secure Action Cable subscription:</p>

        <kbd>cable_ready_stream_from :example_page</kbd>

        <%= cable_ready_stream_from :example_page %>

        <p style="margin-top: 1rem;">Every user looking at a page subscribed to the <ins>:example_page</ins> channel will receive the same broadcasts.</p>

        <p>You can call <ins>cable_ready</ins> <a href="https://cableready.stimulusreflex.com/guide/cableready-everywhere" target="_blank">pretty much anywhere</a> in your application. Try it in your <kbd>rails console</kbd> now:</p>

        <kbd>include CableReady::Broadcaster<br>cable_ready[:example_page].text_content("#cable_ready_stream_from_output", text: "Hello from the console!").broadcast</kbd>

        <p style="margin-top: 1rem;">Any message you send will appear in the <ins>#cable_ready_stream_from_output</ins> DIV below &mdash; even if you <i>open multiple tabs</i>.</p>

        <div id="cable_ready_stream_from_output" style="height: 2rem; font-weight: bolder; border: coral 2px dashed; padding: 0.15rem 0.4rem;"></div>

        <p style="margin-top: 1rem;">While it's easy to <a href="https://cableready.stimulusreflex.com/guide/broadcasting-to-resources" target="_blank">create your own custom Action Cable channels</a>, <ins>cable_ready_stream_from</ins> will be the first tool you reach for, because it doesn't require any additional code.</p>

        <p>Specify Active Record models or compound qualifiers to go full-ninja: 🥷</p>

        <kbd>cable_ready_stream_from current_user</kbd><br>

        <kbd style="margin-top: 0.3rem;">cable_ready_stream_from @post, :comments</kbd>

        <p style="margin-top: 1rem;">These examples barely scrape the surface of what's possible. Be sure to check out the <a href="https://cableready.stimulusreflex.com/guide/identifiers" target="_blank">Stream Identifiers</a> chapter.</p>
      </article>

      <article>
        <h3>Updatable: magically update the DOM when server-side data changes</h3>

        <p>The <ins>updates_for</ins> helper allow you to designate sections of your page that will <a href="https://cableready.stimulusreflex.com/guide/updatable" target="_blank">update automatically</a> with new content when an Active Record model changes. 🤯</p>

        <small>It's difficult to demonstrate this feature without creating a temporary model and a migration; a road to hell, paved with good intentions. However, you likely have these models (or similar) in your application. Uncomment, tweak if necessary and follow along!</small>

        <p style="margin-top: 1rem;">First, call <ins>enable_updates</ins> in your model. You can use it on associations, too.</p>

        <kbd> class User < ApplicationRecord<br>
                &nbsp;&nbsp;enable_updates<br>
                &nbsp;&nbsp;has_many :posts, enable_updates: true<br>
              end<br>
              <br>
              class Post < ApplicationRecord<br>
                &nbsp;&nbsp;belongs_to :user<br>
              end
        </kbd>

        <p style="margin-top: 1rem;">By default, updates will be broadcast when any CRUD action is performed on the model. You can customize this behavior by passing options such as <ins>on: [:create, :update]</ins> or <ins>if: -> { id.even? }</ins>.</p>

        <p>Next, use the <ins>updates_for</ins> helper to create one or more containers that will receive content updates.</p>

        <kbd> &lt;%= cable_ready_updates_for current_user do %&gt;<br>
                &nbsp;&nbsp;&lt;%= current_user.name %&gt;<br>
              &lt;% end %&gt;
        </kbd>

        <!--
        <%#= cable_ready_updates_for current_user do %>
          <p style="margin-top: 1rem;"><%#= current_user.name %></p>
        <%# end %>
        -->

        <p style="margin-top: 1rem;">Update the current user in Rails console, and your page instantly reflects the new name. 🪄</p>

        <p>Specify the class constant to get updates when records are created or deleted:</p>

        <kbd> &lt;%= cable_ready_updates_for User do %&gt;<br>
              &nbsp;&nbsp;&lt;ul&gt;<br>
              &nbsp;&nbsp;&lt;% @users.each do |user| %&gt;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;&lt;%= user.name %&gt;&lt;/li&gt;<br>
              &nbsp;&nbsp;&lt;% end %&gt;<br>
              &nbsp;&nbsp;&lt;/ul&gt;<br>
              &lt;% end %&gt;
        </kbd>

        <!--
        <%#= cable_ready_updates_for User do %>
          <ul style="margin-top: 1rem;">
            <%# @users.each do |user| %>
              <li><%#= user.name %></li>
            <%# end %>
          </ul>
        <%# end %>
        -->

        <p style="margin-top: 1rem;">Update when new posts are created by the current user:</p>

        <kbd> &lt;%= cable_ready_updates_for current_user, :posts do %&gt;<br>
              &nbsp;&nbsp;&lt;ul&gt;<br>
              &nbsp;&nbsp;&lt;% @posts.each do |post| %&gt;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;&lt;%= post.title %&gt;&lt;/li&gt;<br>
              &nbsp;&nbsp;&lt;% end %&gt;<br>
              &nbsp;&nbsp;&lt;/ul&gt;<br>
              &lt;% end %&gt;
        </kbd>

        <!--
        <%#= cable_ready_updates_for current_user, :posts do %>
          <ul style="margin-top: 1rem;">
            <%# @posts.each do |post| %>
              <li><%#= post.title %></li>
            <%# end %>
          </ul>
        <%# end %>
        -->

        <p style="margin-top: 1rem;">One major advantage of the Updatable approach is that each visitor sees <b>personalized content</b>. This is difficult with a WebSockets broadcast, where every subscriber receives the same data.</p>

        <p>Instead, Updatable notifies all subscribers that an update is available, prompting each client to make a fetch request and refresh sections of the page.</p>

        <p>There's more to <a href="https://cableready.stimulusreflex.com/guide/updatable" target="_blank">Updatable</a> than what's covered here... <i>but, not much more</i>. It really is that simple.</p>
      </article>

      <article>
        <p>If you're finished with this example page and resource controller, you can destroy them:</p>

        <kbd>rails destroy stimulus_reflex example</kbd>
      </article>

      <p>As always, please drop by the <a href="https://discord.gg/stimulus-reflex" target="_blank">StimulusReflex Discord server</a> if you have any questions or need support of any kind. We're incredibly proud of the community that has formed around these libraries, and we discuss everything from JavaScript/Ruby/CSS to View Component/Phlex to databases and CRDTs. <b>We'd love to hear what you're building with StimulusReflex and CableReady.</b></p>

      <p>You can find the documentation for StimulusReflex <a href="https://docs.stimulusreflex.com" target="_blank">here</a> and CableReady <a href="https://cableready.stimulusreflex.com" target="_blank">here</a>.</p>
    </main>
    <div class="fireworks" style="position: fixed; bottom: 0; width: 100vw; height: 100vh; pointer-events: none;"></div>
  </body>
</html>

app/views/layouts/_footer.html.erb
<footer class="mb-0 bg-blue-500 text-white h-[60px] shadow-md w-full">
</footer>

app/views/layouts/_header.html.erb
<header class="bg-blue-500 w-full shadow-md">
    <nav class="h-[60px] mx-auto px-4 md:container text-white flex items-center justify-between">
        <div>
            <a href="#"><span><i class="fa-solid fa-water"></i> DRIFT</span></a>
        </div>
        
        <div class="hidden md:flex desktop-menu">
            <ul class="flex flex-row items-center ">
                <% if Current.user %>
                    <li class="px-2 py-2 hover:bg-orange-400 rounded border border-transparent">
                        <%= link_to 'Maps', maps_path %>
                    </li>
                    <li class="px-2 py-2 hover:bg-orange-400 rounded border border-transparent">
                        <%= link_to 'Explore', streams_path %>
                    </li>
                    <li>
                        <%= link_to "Log out", logout_path, method: :delete, class: "px-2 py-2 hover:bg-orange-400 rounded border border-transparent" %>
                    </li>
                <% else %>
                    <li class="px-2 py-2 hover:bg-orange-400 rounded border border-transparent"><a href="/sign_up">Sign Up</a></li>
                    <li class="px-2 py-2 hover:bg-orange-400 rounded border border-transparent"><a href="/sign_in">Log in</a></li>
                <% end %>
            </ul>
        </div>

        <!-- Checkbox and Hamburger Menu Icon -->
        <input type="checkbox" id="menu-toggle" class="hidden">
        <label for="menu-toggle" class="md:hidden cursor-pointer">
            <i id="menu-toggle-bars" class="fa-solid fa-bars text-white text-xl"></i>
            <i id="menu-toggle-x" class="fa-solid fa-x text-white text-xl"></i>
        </label>

        <div class="mobile-menu w-full text-gray-900 bg-white border-gray-200">
            <ul class="flex flex-col items-center px-4 py-8 gap-2">
                <% if Current.user %>
                    <li class="w-full">
                    <%= link_to maps_path, class: "block w-full h-full px-4 py-2 hover:bg-gray-100 rounded border border-transparent" do %>
                        <i class="fa-solid fa-map text-green-500 mr-2"></i> Maps
                    <% end %>
                    </li>
                    <li class="w-full">
                    <%= link_to streams_path, class: "block w-full h-full px-4 py-2 hover:bg-gray-100 rounded border border-transparent" do %>
                        <i class="fa-solid fa-compass mr-2 text-blue-500"></i> Explore
                    <% end %>
                    </li>
                    <li class="w-full">
                    <%= link_to logout_path, method: :delete, class: "block w-full h-full px-4 py-2 hover:bg-gray-100 rounded border border-transparent" do %>
                        <i class="fa-solid fa-sign-out-alt mr-2 text-gray-900"></i> Log out
                    <% end %>
                    </li>
            <% else %>
                <li class="w-full">
                    <a class="block w-full h-full px-4 py-2 hover:bg-gray-100 rounded border border-transparent" href="/sign_in">
                        <i class="fa-solid fa-sign-in-alt mr-2"></i> Log in
                    </a>
                </li>
                <li class="w-full">
                    <a class="block w-full h-full px-4 py-2 hover:bg-gray-100 rounded border border-transparent" href="/sign_up">
                        <i class="fa-solid fa-user-plus mr-2"></i> Sign Up
                    </a>
                </li>
            <% end %>            
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>DriftRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Add these lines within the <head> section -->
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
  </head>

  <body class="mx-auto flex flex-col h-full">
    <%= render 'layouts/header' %>
    <main class="flex-grow w-full p-0 m-0">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/maps/components/_layers.html.erb
<input type="checkbox" id="layers-toggle" class="hidden-checkbox">

<label class="layers-toggle-button" for="layers-toggle">
    <div class="w-[120px] bg-white p-2 bg-white rounded-md shadow-md hover:bg-gray-200 hover:cursor-pointer">
        <p class="text-lg flex justify-center items-center">
            <span class="flex justify-center items-center bg-blue-500 mr-2 rounded-md p-2 text-white">
                <i class="fa-solid fa-layer-group"></i>
            </span>
            Layers
        </p>
    </div>
</label>

<div class="layers-content bg-white p-4 bg-white rounded-md shadow-md mb-2 w-[368px]">
    <div class="flex justify-between text-2xl py-2">
        <h2 class="font-bold">Map Layers</h2>
        <label for="layers-toggle" class="hover:text-blue-500 hover:cursor-pointer"><i class="fa-solid fa-xmark"></i></label>
    </div>

    <!--
    <p class="text-xl flex align-center justify-between mb-2">Boat Ramps
        <label class="switch">
            <input checked type="checkbox">
            <span class="slider round"></span>
        </label>
    </p>
    <p class="text-xl flex align-center justify-between mb-2">Rapids
        <label class="switch">
            <input checked type="checkbox">
            <span class="slider round"></span>
        </label>
    </p>
    
    <p class="text-xl flex align-center justify-between">Easements
        <label class="switch">
            <input checked type="checkbox">
            <span class="slider round"></span>
        </label>
    </p>
    -->

    <p class="text-xl flex align-center justify-between mb-2">
        <span><i class="fa-solid fa-land"></i> Public/Private Land</span>
        <label class="switch">
            <input checked type="checkbox" id="toggle-co-public-private-land-layer">
            <span class="slider round"></span>
        </label>
    </p>

    <p class="text-xl flex align-center justify-between mb-2">
        <span><i class="fa-solid fa-shop"></i> Fly Shops</span>
        <label class="switch">
            <input checked type="checkbox" id="toggle-fly-shop-layer">
            <span class="slider round"></span>
        </label>
    </p>
</div>

app/views/maps/components/_popup.html.erb
<div class="bg-white py-2 px-4 rounded-md shadow-md w-[368px]">
    <div class="flex justify-end text-2xl pb-2">
        <p class="hover:text-blue-500 hover:cursor-pointer">
            <i class="fa-solid fa-xmark"
                data-reflex="click->MapReflex#hide_search_popup"
                data-reflex-dataset="combined"
                data-id="<%= stream.id %>"
            ></i></p>
    </div>
    <img src="https://www.flyfishingcolorado.net/wp-content/uploads/2020/05/MG_2785JPG-scaled.jpg" alt="Colorado River" class="w-full h-[200px] object-cover mb-4">
    <h2 class="text-lg">
        <!-- TODO: Import favorite button -->
        <!-- <i class="fa-regular fa-star text-yellow-500 text-xl hover:text-green-500"></i> -->
        <span class="font-bold"><%= stream.stream_name %></span> <%= stream.location %>
    </h2>
    <p class="text-lg">Location: <%= stream.watershed %>, <%= stream.state %></p>
    <p class="text-lg">Flow: 126 cfs</p>
    <%= link_to "View Details", streams_path, class: "text-blue-600 text-lg no-underline hover:underline mr-2" %></td>
    <!-- Allow users to favorite flows -->
    <!-- Check if user is logged in: then allow user to favorite, and maybe use the outline star-->
    <!-- Check if user has favorited-->
    <% if current_user %>
        <!-- Check if user has favorited / display empty or full star depending, maybe darken favorite -->
        <a href="#" class="text-blue-500 text-lg">Add to Favorites</a>
    <% end %>
</div>

app/views/maps/components/_results.html.erb
<% if !streams.nil? %>
    <section class="bg-white p-2 rounded-md shadow-md w-[368px] mt-2">
        <% if streams.length > 0 %>
            <% streams.each do |stream| %>
                <div class="p-2 rounded-md hover:bg-gray-100 hover:cursor-pointer"
                    data-reflex="click->MapReflex#display_search_popup"
                    data-reflex-dataset="combined"
                    data-id="<%= stream.id %>">
                <!-- search result display_search_popup -->
                    <div class="flex items-center">
                        <i class="text-lg fa-solid fa-water text-blue-600 mr-2"></i>
                        <span class="flex w-full justify-between">
                        <!-- TODO: Truncate text as opposed to wrapping -->
                            <span class="text-lg mr-2">
                                <%= stream.stream_name %>
                                <span class="text-sm text-gray-500">
                                    <%= stream.location %>
                                </span>
                            </span>
                            <span class="text-sm text-gray-500"><%= stream.state %></span>
                        </span>
                    </div>
                </div>
            <% end %>
        <% else %>
            <p class="text-lg text-gray-500">No results found</p>
        <% end %>
    </section>
<% end %>

app/views/maps/components/_search.html.erb
<%= form_with(html: { autocomplete: "off" }) do |form| %>
    <div class="relative">
        <%= form.text_field :query,
            value: params[:query],
            data: { reflex: "input->MapReflex#search" },
            placeholder: "Search",
            class: "w-[368px] pl-8 pr-2 py-2 border-2 border-gray-200 rounded-lg bg-gray-50 focus:outline-none"
        %>
        <i class="fa-solid fa-search text-lg absolute left-2 top-1/2 transform -translate-y-1/2"></i>
    </div>
<% end %>

<section id="map-search-results-table"></section>

<!-- 
# create a partial, i think i should also include the search results in the partial
# 
# i want to create a basic search form

# mvp
# and i want to render a basic table of results,
# that when clicked goes to the river on the map
# i also want to add landmarks, like fly shops, 
# how do i pass search result to map?

# v2. parks, campgrounds
-->

app/views/maps/show.html.erb
<section 
  class="relative"
  id='map'
  style='height: 100%; width: 100%;'
  data-mapbox-access-token="<%= ENV["MAPBOX_ACCESS_TOKEN"] %>">
  # TODO: find a better way to pass access token to mapbox

  <div id="tools-overlay" class="absolute top-0 left-0 mx-4 my-2 z-10">
    <%= render 'maps/components/search', locals: {flows: @flows } %>
  </div>

  <div id="popup-overlay" class="absolute top-5 right-5 z-10"></div>

  <!-- Map Legend -->
  <div id="layers-overlay" class="absolute bottom-5 left-5 z-10">
    <%= render 'maps/components/layers' %>
  </div>
</section>

<%#= javascript_pack_tag "application" %>

app/views/reports/_form.html.erb
<%= form_with model: [@flow, @flow.reports.build ] do |form| %>
    <p>
        <%= form.label :author %><br>
        <%= form.text_field :author %>
    </p>
    <p>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
    </p>
    <p>
        <%= form.label :rating %><br>
        <%= form.number_field :rating %>
    </p>
    <p class="mb-4">
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </p>

    <div>
        <%= form.submit class: "bg-blue-500 hover:bg-orange-500 text-white font-bold py-2 px-4 rounded" %>
    </div>
<% end %>

app/views/reports/_report.html.erb
<p>
    <strong>Author:</strong>
    <%= report.author %>
</p>
<p>
    <strong>Report:</strong>
    <%= report.body %>
</p>
<p>
    <strong>Rating:</strong>
    <%= report.rating %>
</p>
<p>
<%= link_to "Destroy Report",
    [report.flow, report], 
    method: :delete,
    data: { confirm: "Are you sure you want to delete this report?"},
    class: "w-[135px] block text-center text-white px-2 py-1 bg-red-600 hover:bg-yellow-500 rounded-md" %>
</p>

app/views/streams/_cards.html.erb
    <% streams.each do |stream| %>
        <div class="py-4 px-4 my-4 mx-4 border rounded-xl flex justify-between items-center odd:bg-white even:bg-gray-50">
            <span class="flex items-center">
            
            <span data-id="favorite_stream_<%= stream.id %>_card">
                <%= render "components/buttons/favorite", 
                stream: stream,
                current_user: current_user, 
                is_favorited: current_user&.favorited_streams&.include?(stream) %>
            </span>
            <span class="flex flex-col mx-4">
                <span class="text-md font-semibold">
                    <%= stream.stream_name %>    
                </span>
                
                <span class="text-sm"><%= stream.location %>, <%= stream.state %></span>
            </span>
        </span>
        <span class="whitespace-nowrap"><td class="px-4 py-4 align-right text-lg"><%= stream.stream_flows.last.flow_rate %> cfs</td></span>
    </div>
<% end %>